name: Build
on:
  push:
    paths:
      - 'assets/js/list.min.js'
      - 'assets/js/main.js'
      - 'index_dev.html'
      - 'Makefile'
      - '!.github/workflows/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@latest
      with:
        token: ${{ secrets.ACTIONS_PAT }}
    - name: Build arquivos
      run: make
    - name: Commit builds
      uses: EndBug/add-and-commit@latest
      with:
        add: '["index.html", "assets/js/all.min.js"]'
        author_name: pxlcmrd
        author_email: raphael.toledo@outlook.com
        message: 'Build'

