name: Build
on:
  push:
    paths:
      - 'js/externs.js'
      - 'js/list.min.js'
      - 'js/main.js'
      - 'index.html'
      - '!.github/workflows/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build arquivos
      run: make
    - name: Commit builds
      uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
      with:
        add: '["index.html", "js/all.min.js"]'
        author_name: pxlcmrd
        author_email: raphael.toledo@outlook.com
        message: 'Build'

