name: JSDoc
on:
  push:
    paths:
      - 'assets/js/externs.js'
      - 'assets/js/app.js'
      - '!.github/workflows/**'
      - '.github/workflows/jsdoc.yml'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Build
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./assets/js/app.js
          output_dir: ./docs
          #config_file: conf.json
          template: minami
          front_page: README.md
      - name: Deploy
        uses: EndBug/add-and-commit@latest
        with:
          add: '["./docs/**"]'
          author_name: pxlcmrd
          author_email: raphael.toledo@outlook.com
          message: 'Documentação'
