name: JSDoc
on:
  push:
    paths:
      - 'js/externs.js'
      - 'js/main.js'
      - '!.github/workflows/**'
      - '.github/workflows/jsdoc.yml'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5 minutes
        uses: whatnick/wait-action@master
        with:
          time: '300s'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./js/main.js
          output_dir: ./docs
          #config_file: conf.json
          template: minami
          front_page: README.md
      - name: Deploy
        uses: EndBug/add-and-commit@v7
        with:
          add: '["./docs/**"]'
          author_name: pxlcmrd
          author_email: raphael.toledo@outlook.com
          message: 'Documentação'
